### ISSUE TITLE
Default LC_TYPE

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/clipboardy#15]
> pbcopy and pbpaste use locale environment variables to determine the encoding to be used for input and output. For example, absent other locale settings, setting the environment variable LANG=en_US.UTF-8 will cause pbcopy and pbpaste to use UTF-8 for input and output. If an encoding cannot be determined from the locale, the standard C encoding will be used. Use of UTF-8 is recommended. Note that by default the Terminal application uses the UTF-8 encoding and automatically sets the appropriate locale environment variable.

https://github.com/Microsoft/vscode/issues/26502#issuecomment-301043547

Should we set `UTF-8` as default encoding, if no specified?

**Comment by sindresorhus** [comment]
We should set it regardless.
