### ISSUE TITLE
EOL handling

### ISSUE THREAD

**Issue by SebastianZaha** [sindresorhus/clipboardy#17]
Hello, I am using this module in a VSCode plugin, and noticed that on windows, when copying and pasting EOL characters the behavior is that they are sometimes stripped. The text should be pasted verbatim, right?

I added a test that fails to explain what I mean: https://github.com/SebastianZaha/clipboardy/commit/481c9b409bbf6445e05e2e0b91f125f003d148f4

**Comment by sindresorhus** [comment]
> The text should be pasted verbatim, right?

Yes

>  added a test that fails to explain what I mean: SebastianZaha/clipboardy@481c9b4

Would you mind submitting it as a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by floatdrop** [comment]
Fixed in #23
