### ISSUE TITLE
Probably doesn't work as expected on some Windows machines

### ISSUE THREAD

**Issue by notatestuser** [sindresorhus/clipboardy#2]
node-copy-paste uses the same method of execing `clip` on Windows but I had some trouble with Unicode characters on systems running ASCII-only code pages (for instance, those configured with en-US locales).

I've addressed this in my [fork of node-copy-paste](https://github.com/notatestuser/node-copy-paste/tree/master/platform/fallbacks) by setting the code page to `65001` before running `clip.exe`.

`execa` might already be handling this but I'm not sure.

**Comment by sindresorhus** [comment]
Tests are passing on Windows. Happy to look more into this if you submit a [failing test](https://github.com/avajs/ava#failing-tests) :)

https://github.com/sindresorhus/clipboardy/blob/0a097ac37fcaa504c53278c9bb80c98428cb6c4f/test.js#L20-L33

https://ci.appveyor.com/project/sindresorhus/clipboardy/branch/master

**Comment by notatestuser** [comment]
There's no need: the existing tests fail themselves on my Windows 10 (build 10240) machine with a default code page of 437. I've been trying to reproduce this in Appveyor without much luck.
