### ISSUE TITLE
Can't copy more than 32660 characters

### ISSUE THREAD

**Issue by xconverge** [sindresorhus/clipboardy#24]
Having a problem on windows working with more than 32660 characters and this library.

I believe this is the issue:
https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string/28452546#28452546

Perhaps clipboardy needs to break it up into chunks before processing the data

Related where this was seen including a file of text with this many characters:
https://github.com/VSCodeVim/Vim/issues/1726

**Comment by SamVerschueren** [comment]
The first question that comes up is, why would you actually want to copy so many characters? Care to elaborate on the use case?

**Comment by xconverge** [comment]
Yea sure of course

In VIM, if you delete characters, it inherently also copies them for ease of pasting later on.

So if you select a lot of characters and press d to delete, it will also do a copy and call this library. The user is most likely going to see this when deleting, however it is not unreasonable to say they could just as easily want to copy the whole chunk and paste it elsewhere.

Also for a bit of unrelated context in case I come back a few more times with questions or other issues, with vanilla settings, VIM does NOT use the system clipboard so we never use this library. However, many users (myself included) like to change a vim setting to use the system clipboard. Once that is enabled, all delete, and copy actions use clipboardy.

**Comment by sindresorhus** [comment]
This will be fixed soon. We just need to iron out the last issue with the updated Windows binary.

**Comment by floatdrop** [comment]
Fixed in #19

**Comment by xconverge** [comment]
Awesome! Thanks guys, will be patiently waiting for the release now :) Appreciate it!

**Comment by floatdrop** [comment]
@xconverge shipped in `1.1.3` 🎉

**Comment by xconverge** [comment]
@floatdrop @sindresorhus Thanks guys!
