### ISSUE TITLE
Some unicode characters are broken

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/clipboardy#25]
On Windows some unicode characters are broken while copy-pasted:

<img width="539" alt="screen shot 2017-06-10 at 12 21 18" src="https://user-images.githubusercontent.com/365089/27000971-659b6a18-4dd7-11e7-8595-57f957dc785c.png">

It could be bug in [win-clipboard](https://github.com/sindresorhus/win-clipboard) – but there is [test](https://github.com/sindresorhus/win-clipboard/blob/master/test.bat#L47) with same characters, which passes.

**Comment by DavidAnson** [comment]
I don't have a proper development environment available, but have looked at the code and played around with `copy.exe` pasting into `notepad.exe`.

I think there is a bug in `win-clipboard`'s `copy.c` where `hgMem` points to `wchar` data, but is NULL-terminated with a `char`. This violates the `CF_UNICODETEXT` specification: https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168(v=vs.85).aspx

With the fix below applied, copying the characters from the example above (line 393) pastes correctly into Notepad.

The first part of the fix allocates room for a `wchar` at the end of the buffer and asks the API to zero-init the entire buffer. That makes the second part unnecessary and it is removed.

```diff
diff --git a/copy.c b/copy.c
index 31d77e5..8503143 100644
--- a/copy.c
+++ b/copy.c
@@ -38,7 +38,7 @@ int wmain() {
 		return 1;
 	}
 
-	HANDLE hgMem = GlobalAlloc(GMEM_MOVEABLE, cbSize + 1);
+	HANDLE hgMem = GlobalAlloc(GMEM_MOVEABLE | GMEM_ZEROINIT, cbSize + sizeof(wchar_t));
 	LPBYTE lpData = GlobalLock(hgMem);
 
 	cbSize = 0;
@@ -51,8 +51,6 @@ int wmain() {
 		free(prev);
 	}
 
-	lpData[cbSize] = 0;
-
 	GlobalUnlock(hgMem);
 	OpenClipboard(NULL);
 	EmptyClipboard();
```

Upon review, the corresponding bug does not appear to be present in `paste.c`, but I have not experimented with it at all.

Hope this helps!

**Comment by floatdrop** [comment]
@DavidAnson thanks for pointing this out! 🎉
