### ISSUE TITLE
EOL problem

### ISSUE THREAD

**Issue by bjc5233** [sindresorhus/clipboardy#27]
![clip](https://user-images.githubusercontent.com/1620471/27649295-e6e8eb1e-5c63-11e7-9f69-b63841a4a899.png)

I'm use this moudle in win10, it work nice, 
but when use paste, i get 【\r\r\n】, actually i want 【\r\n】;
it show right in terminal, but in file it will bing too many blank lines.

I have checked #17 
I didnot use copy.exe, I copy words manual

**Comment by floatdrop** [comment]
Maybe Node.JS coerce `\n` to system EOL, which on Windows is `\r\n`. Care to add failing test case?

**Comment by floatdrop** [comment]
Moving to rust fixed this problem:

![virtualbox_msedge - win10_10_11_2017_00_23_48](https://user-images.githubusercontent.com/365089/32625242-8c69e1ee-c5ad-11e7-8202-493af108f542.png)

But introduced dependency on `VCRUNTIME140.dll` which can be installed with https://www.microsoft.com/en-us/download/details.aspx?id=52685
