### ISSUE TITLE
Return more than one item?

### ISSUE THREAD

**Issue by piotryordanov** [sindresorhus/clipboardy#29]
I know that `pbpaste` returns the last item copied to clipboard. Is there however a way to return a bigger list of items, say the last 100?

**Comment by sindresorhus** [comment]
No, you would have to launch a daemon that watches the clipboard. Out of scope for this module.

**Comment by piotryordanov** [comment]
Understood. Thanks!
Do you happen to know a cli module that watches the clipboard?

**Comment by sindresorhus** [comment]
https://npms.io/search?q=clipboard+watch
