### ISSUE TITLE
Error when installing clipboardy

### ISSUE THREAD

**Issue by Jamunadevi-Vijayan** [sindresorhus/clipboardy#31]
When giving "npm install --save clipboardy" getting below error,
**_.
.
.
406 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
407 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
408 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
408 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
408 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
408 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
409 verbose stack Error: ENOENT: no such file or directory, rename 'C:\QFL-Latest\node_modules\clipboardy\node_modules\cross-spawn' -> 'C:\QFL-Latest\node_modules\execa\node_modules\cross-spawn'
409 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\action\move.js:86:7
409 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:11:16
409 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\rename.js:11:14
409 verbose stack     at CB (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:93:17)
409 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
409 verbose stack
409 verbose stack Error: ENOENT: no such file or directory, rename 'C:\QFL-Latest\node_modules\clipboardy\node_modules\cross-spawn' -> 'C:\QFL-Latest\node_modules\execa\node_modules\cross-spawn'
409 verbose stack     at Error (native)_**

**Comment by sindresorhus** [comment]
Use the npm issue tracker for npm install issues.
