### ISSUE TITLE
Issues with Ubuntu ... ?

### ISSUE THREAD

**Issue by goessner** [sindresorhus/clipboardy#36]
When using clipboardy with

     Operating system: _Ubuntu 16.04 LTS_
       VSCode version: _ 1.20.1_
     Markdown+Math version: 2.1.0

by code ...
```js
if (!cb) cb = require('clipboardy');
     cb.write(clipTmpl(mdit.render(doc.getText())))
       .then(()=>vscode.window.showInformationMessage('Html copied to clipboard!'),
             ()=>vscode.window.showInformationMessage('Html copying to clipboard failed!'));
```
... it says 'Html copying to clipboard failed!', whereas with all other operating systems it seems to work well. See ...

https://github.com/goessner/mdmath/issues/44
https://github.com/goessner/mdmath/issues/36

Is it simply so, that Ubuntu is not supported by `clipboardy`?

thanks

**Comment by LCAR979** [comment]
@goessner It turns out that you must install dependency to make mdmath work. Please see [this pull request](https://github.com/sindresorhus/clipboard-cli/pull/2/commits/ed1ac99f1bb66bda88263d0b57eb34d300807c35) and [the related issue](https://github.com/sindresorhus/clipboard-cli/issues/1)

**Comment by floatdrop** [comment]
Clipboardy ships with precompiled binary for Linux - so you do not need ‘xsel’ installed.

@goessner can you post full error message from clipboardy?

**Comment by goessner** [comment]
Thanks for having solved this issue.
@floatdrop: What does ' ... ships with precompiled binary for Linux ... ' mean?
In `mdmath`'s `package.json` is clipboardy listed with all its dependencies. So do I need to loist 'xsel' here explicitely somehow?

How do you want me to post the full error message ... as a simple link ?

**Comment by floatdrop** [comment]
> What does ' ... ships with precompiled binary for Linux ... ' mean?
We literally ship xsel inside npm package – https://github.com/sindresorhus/clipboardy/blob/master/fallbacks/linux/xsel

> How do you want me to post the full error message ... as a simple link ?

Something like this should do the trick:

```js
if (!cb) cb = require('clipboardy');
     cb.write(clipTmpl(mdit.render(doc.getText())))
       .then(()=>vscode.window.showInformationMessage('Html copied to clipboard!'),
             (err)=>vscode.window.showInformationMessage(err.message));
```

**Comment by goessner** [comment]
.. it works now ..

https://github.com/sindresorhus/clipboardy/issues/36

thanks
