### ISSUE TITLE
Support primary/secondary/clipboard on X (Linux)

### ISSUE THREAD

**Issue by rektide** [sindresorhus/clipboardy#37]
X window has three different selection buffers- a primary, a secondary, and a clipboard. It'd be great to be able to use this library to access any.

Atm I'm still using the unpublished https://github.com/rawiroaisen/node-xsel because of this.

**Comment by sindresorhus** [comment]
This module is intentionally simple. There are other ways to set the clipboard on macOS too. And we could support lots of other types. But I prefer to just do the minimum here, do it well, and consistently across platforms. So I'm gonna decline this.
