### ISSUE TITLE
Can we get complex clipboard data?

### ISSUE THREAD

**Issue by s-a** [sindresorhus/clipboardy#4]
Hi @sindresorhus,

are we able to get informations wether the user copied some files from filemanager to clipbard and/or set it vice versa? I m looking for such a functionaltity for an electron driven filemanager application.

**Comment by sindresorhus** [comment]
No, sorry. This is focused on text only.

**Comment by venikman** [comment]
😢 Could you give an advice what to do if I want to copy an array?

**Comment by floatdrop** [comment]
@venikman you can copy result of `JSON.stringify`, if this is suitable for you.

**Comment by boynet** [comment]
if anyone found a way to do it using node tag me pls
