### ISSUE TITLE
Get image from system clipboard

### ISSUE THREAD

**Issue by LitoMore** [sindresorhus/clipboardy#40]
Is there any way to retrieve the image from system clipboard?

It seems the `pbpaste` not support read the image from clipboard.

**Comment by sindresorhus** [comment]
No, that's outside the scope of this module. Would be too complex to do it consistently cross-platform and that's not something I want to maintain.

Related https://github.com/sindresorhus/clipboardy/issues/4 https://github.com/sindresorhus/clipboardy/issues/37

**Comment by inevity** [comment]
This limit should be mentioned in the readme.
