### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/clipboardy#60]
We can use `document.execCommand` or the Async Clipboard API to create a 1:1 implementation for browsers.

See: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

cc @sindresorhus

**Comment by sindresorhus** [comment]
Sure, but only the async APIs can be supported. It should use the Async Clipboard API. Not interested in any fallback for older browsers.

See https://nodejs.org/api/esm.html#esm_conditional_exports on how to add the browser version.

**Comment by Richienb** [comment]
@sindresorhus In that case, how do we handle calls to writeSync and readSync when running in the browser if we want a 1:1 interface?

**Comment by sindresorhus** [comment]
We would just document that those don't work in the browser.

**Comment by Richienb** [comment]
@sindresorhus The latest version of browserify can't seem to recognise the browser field. Do you have an example in another one of your packages?
