### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by snuckdev** [sindresorhus/clipboardy#71]
Could you guys add events like clipboardy.on('paste')?
So it triggers a callback with the data pasted

**Comment by sindresorhus** [comment]
I don't know about Windows or Linux, but on macOS, the only way to get pasteboard events is polling, which is inefficient.

Why do you need a paste event for a Node.js module? The only use-case I can think of is some kind of interactive CLI tool.

**Comment by snuckdev** [comment]
Fixed that with while loops, thanks.
