### ISSUE TITLE
Uncaught Error: spawnSync clipboard_x86_64,exe ENOENT on Windows

### ISSUE THREAD

**Issue by kimlimjustin** [sindresorhus/clipboardy#76]
Clipboardy works well on Linux and on Windows while developing. However, when I tried to build my [app (it's electron app)](https://github.com/kimlimjustin/xplorer), it raises an error:
![image](https://user-images.githubusercontent.com/61906684/131672504-66a3d673-fec9-497a-8b46-da31fdfc97d0.png)

**Comment by kimlimjustin** [comment]
I think this is because the code runs the exe code on Windows, I think this should be fixed by using node js addon API to call C/C++ code natively from javascript instead of running exe file.

**Comment by sindresorhus** [comment]
This is a problem with Electron: https://github.com/electron/electron/issues/9459

Electron also has their own clipboard methods, so you don't really need this package there.
