### ISSUE TITLE
Doesn't works when I launch my app to Heroku

### ISSUE THREAD

**Issue by Ajharul7** [sindresorhus/clipboardy#81]
This is the error i get :
Couldn't find the xsel binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel 

**I made a discord bot and am trying to launch it in Heroku but the clipboardy does not seems to function . I used Windows 10,Node 14.18.3 and Clipboardy 2.3.0**

**Comment by sindresorhus** [comment]
The error message says it all. I don't really know what else I can add to that.

**Comment by Ajharul7** [comment]
Could you provide a solution for it? Is there a way around it?

**Comment by kadistudio** [comment]
is this issue fixed?
