### ISSUE TITLE
Having this error when run in Discord.JS Bot

### ISSUE THREAD

**Issue by kadistudio** [sindresorhus/clipboardy#87]
C:\Users\Kadi\Documents\GitHub\Discord-Bot\Commands\Paimon Menu\namecard.js:13
const clipboard = require("clipboardy");
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Kadi\Documents\GitHub\Discord-Bot\node_modules\clipboardy\index.js from C:\Users\Kadi\Documents\GitHub\Discord-Bot\Commands\Paimon Menu\namecard.js not supported.
Instead change the require of index.js in C:\Users\Kadi\Documents\GitHub\Discord-Bot\Commands\Paimon Menu\namecard.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\Kadi\Documents\GitHub\Discord-Bot\Commands\Paimon Menu\namecard.js:13:19)
    at C:\Users\Kadi\Documents\GitHub\Discord-Bot\Handlers\Commands.js:13:25
    at Array.map (<anonymous>)
    at module.exports (C:\Users\Kadi\Documents\GitHub\Discord-Bot\Handlers\Commands.js:12:52) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.4.0

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
