### ISSUE TITLE
Both xsel and fallback failed

### ISSUE THREAD

**Issue by sankalpguptasymphony** [sindresorhus/clipboardy#91]
I am getting an error - "Both xsel and fallback failed" on Linux machine when running automation tests (headless chrome), is there any solution available to avoid this error?

**Comment by flipphillips** [comment]
Getting same when ssh'd to remote machine via iTerm2 on macOS to linux box. No reason to expect `xsel` to work on macOS of course (`pbcopy` and `pbpaste` are the preferred solution there) but not sure about the fallback, etc.

**Comment by sankalpguptasymphony** [comment]
I was able to progress with my work by using keys Alt+D and Ctrl+V (basically I had to copy a clipboard data into the address bar), which for some reason only working in headless mode (which is fine with me).

I am closing this bug as the same issue is getting disused in https://github.com/sindresorhus/clipboardy/issues/63 as well.

@flipphillips
