### ISSUE TITLE
Browser support in http (non-secure context)

### ISSUE THREAD

**Issue by ForgottenR** [sindresorhus/clipboardy#94]
Currently the Clipboard API only works for secure contexts (https) which makes this library unusable in http. If that's intended probably you should add a simple statement in the readme file (or anywhere you place documentations)?

**Comment by sindresorhus** [comment]
That is intended.

**Comment by sindresorhus** [comment]
Check out https://github.com/sindresorhus/copy-text-to-clipboard for `http`.
